### ISSUE TITLE
ImportError: No module named wall

### ISSUE THREAD

**Issue by mirzap** [turkishviking/Python-Robocode#1]
I'm trying to run main file, but I'm getting this error:

```
#: ~/Python-Robocode$ python main.py 
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from window import MainWindow
  File "/home/home_dir/Python-Robocode/GUI/window.py", line 10, in <module>
    from graph import Graph
  File "/home/home_dir/Python-Robocode/Objects/graph.py", line 8, in <module>
    from wall import Wall
ImportError: No module named wall
```

I've installed libqt4-dev python-qt4-dev and few other packages, what did i miss?

**Comment by turkishviking** [comment]
Hi, sorry for this mistake, I have deleted the wall class.
I 've just re-update the source code, re-download it, and it would work.

It is a beta version, i haven't the time to make the demo robots now.
I'm interseting by a feedback, if you make some base robots i will put them on my source code.

Thank you for testing my program

Regards,

Charlie

Date: Mon, 5 Aug 2013 09:27:48 -0700
